source = Modules/environment.conf
source = Modules/variables.conf
source = Modules/monitors.conf
source = Modules/input.conf
source = Modules/layout.conf
source = Modules/decoration.conf
source = Modules/misc.conf
source = Modules/workspaces.conf
source = Modules/autostart.conf
source = Modules/keybinds/wm.conf
source = Modules/keybinds/apps.conf
source = Modules/keybinds/media.conf
